name: deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0
                  ref: main # 这里选择你触发部署的分支！默认是 master

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: "latest"
                  extended: false # 用 stack 主题需要加这个配置

            - name: Build Web
              run: hugo

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v4
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: L1uYun/l1uyun_blog # 改成你的仓库
                  PUBLISH_BRANCH: pages
                  PUBLISH_DIR: ./public
                  commit_message: ${{ github.event.head_commit.message }}
